/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Conexao_bd;
import Views.Alunos;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.eclipse.persistence.internal.helper.JPAClassLoaderHolder;

/**
 *
 * @author Willian
 */
public class telainicial extends javax.swing.JFrame {
    Conexao_bd c = new Conexao_bd();
      PreparedStatement pst;
      ResultSet rs = null;
    /**  
     * Creates new form telainicial
     */
    public telainicial() {
        
        initComponents();
       
       
        labelusuz.setForeground(Color.red);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelusuz = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelusu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEA Gerenciamento Escolar Versaão 1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelusuz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelusuz.setForeground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Usuario:");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        labelusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/200619122453_16.png"))); // NOI18N
        jMenu1.setText("Alunos");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/Student-id512_44205.png"))); // NOI18N
        jMenuItem1.setText("Cadastros e Consultas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/200619122453_16.png"))); // NOI18N
        jMenu2.setText("Professores");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/edit_user_student_staff_person_icon-icons.com_75492.png"))); // NOI18N
        jMenuItem3.setText("Cadastros e Consultas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/korganizer_task_tasks_list_9501.png"))); // NOI18N
        jMenu3.setText("Dados Escolar");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/Student-id512_44205.png"))); // NOI18N
        menu.setText("Cadastramento");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jMenu3.add(menu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelusu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 538, Short.MAX_VALUE)
                .addComponent(labelusuz, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusuz, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBounds(0, 0, 905, 734);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   this.setExtendedState(MAXIMIZED_BOTH);
   
     Date data = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        labelusuz.setText(format.format(data));
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    
        Professores p = new Professores();
        p.setVisible(true);
        
        
        try {
            c.conecta();
          
            c.executaSql("select perfil from profissional where login ='"+labelusu.getText()+"'");
            c.rs.first();
            if((c.rs.getString("perfil").equals("Professor(a)"))){
                JOptionPane.showMessageDialog(null, "Você não possui permissão para acessar", "Aviso", JOptionPane.ERROR_MESSAGE);
                p.dispose();
                }
            
            
        } catch (SQLException e) {
            Logger.getLogger(telainicial.class.getName()).log(Level.SEVERE, null, e);
        }
        c.desconecta();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
       
                    
         Alunos a = new Alunos();
         a.setVisible(true);
         
          try {
            c.conecta();
          
            c.executaSql("select perfil from profissional where login ='"+labelusu.getText()+"'");
            c.rs.first();
            if(c.rs.getString("perfil").equals("Diretor(a)")){
                  
                 a.jPanel10.setEnabled(true);
            }else{
            
                if((c.rs.getString("perfil").equals("Professor(a)"))){
               
                //Criação de aluno
                a.rgg.setEnabled(false);
                a.nomegg.setEnabled(false);
                a.sobrenomegg.setEnabled(false);
                a.datagg.setEnabled(false);
                a.sex.setEnabled(false);
                a.jButton5.setEnabled(false);
                a.jTable1.setEnabled(false);
                
                //Alterações
                a.busca.setEnabled(false);
                a.rgt.setEnabled(false);
                
                //Matricula
                a.rgmatri.setEnabled(false);
                a.dis.setEnabled(false);
                a.tur.setEnabled(false);
                a.jTextField57.setEnabled(false);
                a.jButton2.setEnabled(false);
                a.jButton3.setEnabled(false);
                a.jButton1.setEnabled(false);
                
                
                
                
                        
                       
                    }else{
                         if((c.rs.getString("perfil").equals("Secretário(a)"))){
                            //Lançar freq
                            a.alteraaluno.setEnabled(false);
                            a.codalu.setEnabled(false);
                            a.jButton9.setEnabled(false);
                            a.codmatri.setEnabled(false);
                            a.jButton10.setEnabled(false);
                            a.jTextField17.setEnabled(false);
                
                
                
                            //Lançar Notas a..setEnabled(false);
                            a.discnota.setEnabled(false);
                            a.jButton12.setEnabled(false);
                            // a.jTextField56.setEnabled(false);
                           // a.jTextField59.setEnabled(false);
                           // a.jTextField61.setEnabled(false);
                           // a.jTextField60.setEnabled(false);
                            a.jButton11.setEnabled(false);
                            a.jButton13.setEnabled(false);
                            a.jTextField32.setEnabled(false);
                            a.nota1.setEnabled(false);
                            a.nota2.setEnabled(false);
                            a.nota3.setEnabled(false);
                            a.nota4.setEnabled(false);
                            a.media.setEnabled(false);
                
                            //Alterações
                            a.busca.setEnabled(false);
                            a.rgt.setEnabled(false);
                            a.jTextField16.setEnabled(false);
                            
                            
                            //Medias
                            a.jTextField22.setEnabled(false);
                            a.jButton15.setEnabled(false);
                            a.jTextPane1.setEnabled(false);
                            a.jButton14.setEnabled(false);
                            
                }
           
                
            }
                 
                  
                  
              
            
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(telainicial.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        c.desconecta();
                                      

       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        Professores p = new Professores();
        p.setVisible(true);
        
        
        try {
            c.conecta();
          
            c.executaSql("select perfil from profissional where login ='"+labelusu.getText()+"'");
            c.rs.first();
            if((c.rs.getString("perfil").equals("Professor(a)"))){
                JOptionPane.showMessageDialog(null, "Você não possui permissão para acessar", "Aviso", JOptionPane.ERROR_MESSAGE);
                p.dispose();
                }
            
            
        } catch (SQLException e) {
            Logger.getLogger(telainicial.class.getName()).log(Level.SEVERE, null, e);
        }
        c.desconecta();
    }//GEN-LAST:event_menuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telainicial().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JLabel labelusu;
    public static javax.swing.JLabel labelusuz;
    public static javax.swing.JMenuItem menu;
    // End of variables declaration//GEN-END:variables
}
